version: "3.9"

services:
  web:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/productiva_db
      - SECRET_KEY=tu-clave-secreta-muy-segura-aqui-cambiar-en-produccion
    command: >
        sh -c "sleep 10 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    tty: true
    stdin_open: true
    networks:
      - productiva_net
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productiva_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Agregar script de inicialización
    command:
      - --default-authentication-plugin=mysql_native_password
      - --wait-timeout=28800
      - --interactive-timeout=28800
    networks:
      - productiva_net
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - web  
    ports:
      - "80:80"
    networks:
      - productiva_net

volumes:
  mysql_data:

networks:
  productiva_net:
    driver: bridge